spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
logging:
  file:
    name: hetu-springboot-example.log
hetu:
  host: xxx:xxx  # [Mandatory]:Hetu HSFabric Host Post, it can be multiple pairs, for example xxx:xx,xxx:xx,xxx:xx
  catalog: hive  # [Mandatory]: Hetu catalog
  schema: default  # [Mandatory]: Hetu schema
  user: xx  # [Mandatory]: Hetu connection user
  password: xx  # [Optional]: Hetu connection password, it is inactive for cluster in normal mode
  ssl: true  # [Mandatory]: Hetu connection use ssl or not, it is false for cluster in normal mode
  tenant: default  # [Mandatory]: the name of compute instance to be visit
